version: '2.0'
services:
##第一个青龙
  q1:
    image: whyour/qinglong:latest
    container_name: ql1
    restart: always
    volumes:
       - ./ql1:/ql/data
    ports:
       - 5801:5700
##第二个青龙
  q2:
    image: whyour/qinglong:latest
    container_name: ql2
    restart: always
    volumes:
       - ./ql2:/ql/data
    ports:
       - 5802:5700
##第三个青龙
  q3:
    image: whyour/qinglong:latest
    container_name: ql3
    restart: always
    volumes:
       - ./ql3:/ql/data
    ports:
       - 5803:5700
 ##第四个青龙
  q4:
    image: whyour/qinglong:latest
    container_name: ql4
    restart: always
    volumes:
       - ./ql4:/ql/data
    ports:
       - 5804:5700
